fieldtype_fields:
  allow_blank:
    type: toggle
  allow_time:
    type: toggle
    default: true
  require_time:
    type: toggle
    default: false
  earliest_date:
    type: text
    default: January 1, 1900
  format:
    type: text
